services:
  - type: web
    name: ypt-study-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LEADERBOARD_CHANNEL_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: CELEBRATION_CHANNEL_ID
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
